name: Build and Publish Container

on: [push, workflow_dispatch]

# Permissions required for automatic semantic version tagging
permissions:
    contents: write

jobs:
  build:
    # Available runners: https://github.com/actions/runner-images
    runs-on: ubuntu-26.04

    steps:
      - name: Build and publish container
        uses: spritely/build/container@ca6231a549f0d2e49774ccc208b77f0f74518482 # v0.27.15
        with:
          registryUsername: ${{ secrets.DOCKER_HUB_USERNAME }}
          registryPassword: ${{ secrets.DOCKER_HUB_TOKEN }}
          registryHost: docker.io
          imageNames: spritelydev/pulumi-dotnet10
          context: ./src
          dockerfile: ./src/Containerfile
